### ISSUE TITLE
error after update module 

### ISSUE THREAD

**Issue by chihpong** [stefanwalther/generator-qsExtension#5]
I have a previous version of generator-qsextension installed on my system. I updated the module by running 'npm update -g generator-qsextension' and 'npm update -g yo'. After the update, 'yo qsextension' generates the following error. 

C:\vmshare\Sense\extensions\test>yo qsextension

Error: Cannot find module 'chalk'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at C:\Users\cli\AppData\Roaming\npm\node_modules\generator-qsextension\app\index.js:10:14
    at Object.<anonymous> (C:\Users\cli\AppData\Roaming\npm\node_modules\generator-qsextension\app\i
ndex.js:205:2)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)

C:\vmshare\Sense\extensions\test>npm ls -g yo
C:\Users\cli\AppData\Roaming\npm
└── yo@1.4.6

C:\vmshare\Sense\extensions\test>npm ls -g generator-qsextension
C:\Users\cli\AppData\Roaming\npm
└── generator-qsextension@0.0.28

Any idea what might be the problem? What is the proper way of upgrading generator-qsextension?

Thanks in advance for your guidance,

**Comment by chihpong** [comment]
I reinstalled node, yo, and generator-qsextension and still got similar error.

C:\vmshare\Sense\extensions\test>yo qsextension
module.js:338
    throw err;
    ^
Error: Cannot find module 'chalk'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at C:\Users\cli\AppData\Roaming\npm\node_modules\generator-qsextension\app\i
ndex.js:10:14
    at Object.<anonymous> (C:\Users\cli\AppData\Roaming\npm\node_modules\generat
or-qsextension\app\index.js:205:2)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)

**Comment by chihpong** [comment]
After trying different versions of npm and generator-qsextension, this combination worked for me.
C:\vmshare\Sense\extensions\test>npm -v
2.5.1

C:\vmshare\Sense\extensions\test>node -v
v0.12.0

C:\vmshare\Sense\extensions\test>npm ls -g generator-qsextension
C:\Users\cli\AppData\Roaming\npm
└── generator-qsextension@0.0.26

**Comment by stefanwalther** [comment]
Thx, but should also work on node.js 11.x ... I'll investigate on this ...
